package Api;
public class Utils {

    //This is your from email
    public static final  String EMAIL = "sahil123rockit@gmail.com";

    //This is your from email password
    public static final String PASSWORD = "here you will put your app password generated by the gmail account";
}